language:
   - cpp

install:
   # gtest install workaround
   - sudo apt-get install libgtest-dev
   - cd /usr/src/gtest
   - sudo cmake .
   - sudo make
   - sudo mv libgtest* /usr/lib/
   - cd "${TRAVIS_BUILD_DIR}"
   # -- workaround end

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest
