language:
    - objective-c

before_install:
    - brew update

install:
    - brew install cmake
    - brew install python3

script:
    # 1. Download gtest library
    - wget https://github.com/hunter-packages/gtest/archive/v1.7.0-hunter-2.tar.gz
    - tar -xf v1.7.0-hunter-2.tar.gz
    - export GTEST_DIR=`pwd`/gtest-1.7.0-hunter-2
    # 2. Build/install gtest (native platform)
    - cd ${GTEST_DIR}
    - mkdir -p _builds/make
    - cd _builds/make
    - cmake -DCMAKE_INSTALL_PREFIX=${GTEST_DIR}/Install/make ../..
    - make install
    # 3. Build universal(iphone + simulator) iOS library
    - cd ${GTEST_DIR}
    - mkdir -p _builds/xcode
    - cd _builds/xcode
    - cmake -GXcode -DCMAKE_TOOLCHAIN_FILE=${GTEST_DIR}/cmake/iOS.cmake -DCMAKE_INSTALL_PREFIX=${GTEST_DIR}/Install/ios ../..
    - xcodebuild -target install
    # 4. Check installed iOS libraries
    - ls ${GTEST_DIR}/Install/ios/*.a
    - lipo -info ${GTEST_DIR}/Install/ios/libgtest.a
