language:
    - objective-c

install:
    - wget https://github.com/ruslo/CMake/archive/ios.universal.2.tar.gz
    - openssl sha1 ios.universal.2.tar.gz
    - tar xf ios.universal.2.tar.gz
    - cmake -HCMake-ios.universal.2 -B_builds/cmake -DCMAKE_USE_SYSTEM_CURL=YES -DCMAKE_BUILD_TYPE=Release
    - cmake --build _builds/cmake --target install

script:
    # 1. Download gtest library
    - wget https://github.com/hunter-packages/gtest/archive/v1.7.0-hunter-6.tar.gz
    - tar -xf v1.7.0-hunter-6.tar.gz
    - cd gtest-1.7.0-hunter-6

    # 2. Build/install gtest (native platform, if needed):
    - cmake -H. -B_builds/make -DCMAKE_INSTALL_PREFIX="`pwd`/_install/make"
    - cmake --build _builds/make --target install

    # 3. Build universal(iphone + simulator) iOS library (Xcode only):
    - cmake -H. -B_builds/ios -GXcode -DCMAKE_INSTALL_PREFIX="`pwd`/_install/ios" -DCMAKE_TOOLCHAIN_FILE="`pwd`/cmake/iOS.cmake"
    - cmake --build _builds/ios --target install --config Debug
    - cmake --build _builds/ios --target install --config Release

    # 4. Check installed iOS libraries (debug + release):
    - ls _install/ios/lib/*.a
    - lipo -info "`find _install/ios -name libgtest.a`"
